### ISSUE TITLE
using signal(3) to ignore SIGCHLD is problematic

### ISSUE THREAD

**Issue by bunny351** [phillbush/xclickroot#11]
Recently (new machine, new Linux Installation) I noticed strange behaviour when launching subprocesses from code that was itself spawned via xclickroot: Tcl code that used `exec` was giving me error messages about lost child processes. It appears that ignoring SIGCHLD is inherited by children, which shouldn't happen - as I understand it the call to signal(3) is merely intended to avoid zombie children.

I recommend using the POSIX-compatible way of avoiding to wait by using sigaction(2) with the SA_NOCLDWAIT option (see also: https://stackoverflow.com/questions/40601337/what-is-the-use-of-ignoring-sigchld-signal-with-sigaction2). Replacing the call to signal(3) with

     struct sigaction sa;
     sa.sa_handler = SIG_DFL;
     sa.sa_flags = SA_NOCLDWAIT;
     sigaction(SIGCHLD, &sa, NULL);

seems to work for me.

**Comment by phillbush** [comment]
Hi, thanks for reporting it.
It should be fixed now.
